# Generated by Django 2.1.7 on 2020-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('boolTest', models.BooleanField(default=False)),
            ],
        ),
    ]
