# Generated by Django 3.0.2 on 2020-02-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userSearch', '0002_auto_20200201_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
