# Generated by Django 3.0.2 on 2020-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSearch', '0003_auto_20200202_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisee',
            name='screen_name',
            field=models.CharField(default='place_holdere', max_length=200),
            preserve_default=False,
        ),
    ]
